### ISSUE TITLE
NPM installation question.

### ISSUE THREAD

**Issue by phrohdoh** [eirikurn/git-dropbox#1]
What does `npm` (which is a `node` package manager [for js]) have to do with `sh`/`bash`?

**Comment by eirikurn** [comment]
Nothing. But it is

1) Simple to publish.
2) Cross platform (the script works on mac/linux).
3) IMO better than curl installer.
4) Simple to install (doesn't everyone have node installed these days).
5) Script automatically goes into the user's path.
6) Optional, you can always clone and move the binary into the path yourself.
